### ISSUE TITLE
Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by GuafterCW** [ausbitbank/stable-diffusion-discord-bot#32]
```
Connected to discord
Guilds: 1
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at request (F:\invokeaidc\stable-diffusion-discord-bot\index.js:230:52)
    at Object.execute (F:\invokeaidc\stable-diffusion-discord-bot\index.js:134:9)
    at CommandClient.<anonymous> (F:\invokeaidc\stable-diffusion-discord-bot\index.js:1059:47)
    at CommandClient.emit (node:events:513:28)
    at Shard.emit (F:\invokeaidc\stable-diffusion-discord-bot\node_modules\eris\lib\gateway\Shard.js:231:27)
    at Shard.wsEvent (F:\invokeaidc\stable-diffusion-discord-bot\node_modules\eris\lib\gateway\Shard.js:2162:22)
    at Shard.onPacket (F:\invokeaidc\stable-diffusion-discord-bot\node_modules\eris\lib\gateway\Shard.js:391:26)
    at Shard._onWSMessage (F:\invokeaidc\stable-diffusion-discord-bot\node_modules\eris\lib\gateway\Shard.js:2286:33)
    at WebSocket.emit (node:events:513:28)
    at Receiver.receiverOnMessage (F:\invokeaidc\stable-diffusion-discord-bot\node_modules\ws\lib\websocket.js:1180:20)
    at Receiver.emit (node:events:513:28)
    at Receiver.dataMessage (F:\invokeaidc\stable-diffusion-discord-bot\node_modules\ws\lib\receiver.js:526:14)
    at Receiver.getData (F:\invokeaidc\stable-diffusion-discord-bot\node_modules\ws\lib\receiver.js:459:17)
    at Receiver.startLoop (F:\invokeaidc\stable-diffusion-discord-bot\node_modules\ws\lib\receiver.js:158:22)
    at Receiver._write (F:\invokeaidc\stable-diffusion-discord-bot\node_modules\ws\lib\receiver.js:84:10) 
```

Any ideas?
I've followed the installing instructions and as I've started it and used /dream came up this error.

**Comment by ausbitbank** [comment]
Line 230 referenced in the error is
`if (!args.model||args.model===undefined||!Object.keys(models).includes(args.model)){args.model=defaultModel}else{args.model=args.model.toLowerCase()}`

Things to check:
Do you have a default model set in invokeai model config ? `invokeai\config\models.yaml`
Do you have a default model set in the bots .env file ?

Make sure the model names are correct, the readme could be outdated and I'm not positive what models and names invokeai installs by default

**Comment by GuafterCW** [comment]
That actually helped me. Thank you. I'm sorry for the circumstances.
