### ISSUE TITLE
Crash: "Unknown interaction"

### ISSUE THREAD

**Issue by jspraul** [ausbitbank/stable-diffusion-discord-bot#5]
On this line (index.js:85 below, but my script is modified): 

https://github.com/ausbitbank/stable-diffusion-discord-bot/blob/f3c2632cd023626b7ff7835e2c157f9c8b8ce781/index.js#L81

```
DiscordRESTError [10062]: Unknown interaction
    at RequestHandler.request ([...]\stable-diffusion-discord-bot\node_modules\eris\lib\rest\RequestHandler.js:75:15)
    at Client.createInteractionResponse ([...]\stable-diffusion-discord-bot\node_modules\eris\lib\Client.js:770:36)
    at CommandInteraction.createMessage ([...]\stable-diffusion-discord-bot\node_modules\eris\lib\structures\CommandInteraction.js:239:55)
    at Client.<anonymous> ([...]\stable-diffusion-discord-bot\index.js:84:97)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

DiscordRESTError [10062]: Unknown interaction
    at RequestHandler.request ([...]\stable-diffusion-discord-bot\node_modules\eris\lib\rest\RequestHandler.js:75:15)
    at Client.createInteractionResponse ([...]\stable-diffusion-discord-bot\node_modules\eris\lib\Client.js:770:36)
    at CommandInteraction.createMessage ([...]\stable-diffusion-discord-bot\node_modules\eris\lib\structures\CommandInteraction.js:239:55)
    at Client.<anonymous> ([...]\stable-diffusion-discord-bot\index.js:85:61)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)```

**Comment by ausbitbank** [comment]
Hmm I haven't had that issue, is it happening on launch for you or only when users are interacting with the bot ?
Can you turn the logging back on to see what the interaction was that triggered this ?

**Comment by jspraul** [comment]
It may only happen when the bot reconnects after receiving the interaction but before processing it.

Unfortunately Windows Update clobbered my command prompt history so I can not offer many additional details yet, I'll add additional logging.

**Comment by ausbitbank** [comment]
I ran into this issue repetitively today during a period of extremely laggy internet connection. Still not sure exactly what causes it but we can stop the crash by changing the line to
` try { await bot.commands.get(interaction.data.name).execute(interaction); await interaction.createMessage({content: 'Your image will be rendered soon :tm:', flags: 64}).catch((e) => {console.log(e)}) }`

I'll push an update shortly

**Comment by jspraul** [comment]
Sounds fixed.
